name: iOS Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    - name: Show Xcode Version
      run: xcodebuild -version
    
    - name: Debug - Show Repository Structure
      run: |
        echo "Repository root contents:"
        ls -la
        echo ""
        echo "Looking for Xcode project files:"
        find . -name "*.xcodeproj" -type d
        echo ""
        echo "TranslatorApp directory contents:"
        ls -la TranslatorApp/ || echo "TranslatorApp directory not found"
    
    - name: Show Available Schemes
      run: |
        xcodebuild -list -project TranslatorApp.xcodeproj
    
    - name: Clean Build Folder
      run: |
        xcodebuild clean -project TranslatorApp.xcodeproj -scheme TranslatorApp
    
    - name: Build for iOS Simulator
      run: |
        xcodebuild build \
          -project TranslatorApp.xcodeproj \
          -scheme TranslatorApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO
    
    - name: Run Swift Tests (if any)
      run: |
        xcodebuild test \
          -project TranslatorApp.xcodeproj \
          -scheme TranslatorApp \
          -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' \
          -configuration Debug \
          CODE_SIGNING_ALLOWED=NO \
        || echo "No tests found or tests failed - continuing build"
    
    # Archive for TestFlight (only on main branch)
    - name: Archive for Distribution
      if: github.ref == 'refs/heads/main'
      run: |
        xcodebuild archive \
          -project TranslatorApp.xcodeproj \
          -scheme TranslatorApp \
          -configuration Release \
          -archivePath ./TranslatorApp.xcarchive \
          -destination 'generic/platform=iOS' \
          CODE_SIGNING_ALLOWED=NO \
        || echo "Archive failed - code signing may be required"
    
    - name: Build Status
      run: echo "✅ iOS build completed successfully!"

  # Future job for TestFlight deployment (requires Apple Developer account setup)
  deploy:
    name: Deploy to TestFlight
    needs: build
    runs-on: macos-latest
    if: github.ref == 'refs/heads/main' && false  # Disabled until secrets are configured
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'
    
    # This job will be enabled once you set up:
    # - Apple Developer Account
    # - App Store Connect API keys
    # - GitHub Secrets for authentication
    
    - name: Deploy to TestFlight
      env:
        APPLE_ID: ${{ secrets.APPLE_ID }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        API_KEY_ID: ${{ secrets.API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
        API_PRIVATE_KEY: ${{ secrets.API_PRIVATE_KEY }}
      run: |
        echo "TestFlight deployment would happen here"
        echo "Enable this job after setting up Apple Developer account and secrets"